include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - build/**
    - android/**
    - linux/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - ios/**
    - web/**
    - lib/**/*_web.dart

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
