// Copyright (C) 2024-2026 Yomitan Authors
// Ported to Dart for MangaJP Study (Q-B3 / GPL-3.0).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Japanese inflection transforms from Yomitan:
// https://github.com/yomidevs/yomitan/blob/67db60ddc2cbd7b5172d777c117e3201d7ddff0f/ext/js/language/ja/japanese-transforms.js
// Helpers: suffixInflection / wholeWordInflection from
// ext/js/language/language-transforms.js
//
// Do not rewrite these rules from scratch to dodge the license.

/// Yomitan commit this table was ported from.
const String kYomitanTransformsCommit =
    '67db60ddc2cbd7b5172d777c117e3201d7ddff0f';

/// Source file in the Yomitan tree.
const String kYomitanTransformsPath =
    'ext/js/language/ja/japanese-transforms.js';

enum InflectionKind { suffix, wholeWord }

class ConditionSpec {
  const ConditionSpec({this.isDictionaryForm = false, this.subConditions});

  final bool isDictionaryForm;
  final List<String>? subConditions;
}

class InflectionRule {
  const InflectionRule({
    required this.kind,
    required this.inflected,
    required this.deinflected,
    required this.conditionsIn,
    required this.conditionsOut,
  });

  const InflectionRule.suffix(
    String inflected,
    String deinflected,
    List<String> conditionsIn,
    List<String> conditionsOut,
  ) : this(
        kind: InflectionKind.suffix,
        inflected: inflected,
        deinflected: deinflected,
        conditionsIn: conditionsIn,
        conditionsOut: conditionsOut,
      );

  const InflectionRule.wholeWord(
    String inflected,
    String deinflected,
    List<String> conditionsIn,
    List<String> conditionsOut,
  ) : this(
        kind: InflectionKind.wholeWord,
        inflected: inflected,
        deinflected: deinflected,
        conditionsIn: conditionsIn,
        conditionsOut: conditionsOut,
      );

  final InflectionKind kind;
  final String inflected;
  final String deinflected;
  final List<String> conditionsIn;
  final List<String> conditionsOut;
}

class TransformSpec {
  const TransformSpec({
    required this.id,
    required this.name,
    required this.rules,
  });

  final String id;
  final String name;
  final List<InflectionRule> rules;
}

/// Yomitan `conditions` map (dictionary-form flags + chaining subconditions).
const Map<String, ConditionSpec> japaneseConditions = {
  'v': ConditionSpec(
    isDictionaryForm: false,
    subConditions: ['v1', 'v5', 'vk', 'vs', 'vz'],
  ),
  'v1': ConditionSpec(isDictionaryForm: true, subConditions: ['v1d', 'v1p']),
  'v1d': ConditionSpec(),
  'v1p': ConditionSpec(),
  'v5': ConditionSpec(isDictionaryForm: true, subConditions: ['v5d', 'v5s']),
  'v5d': ConditionSpec(),
  'v5s': ConditionSpec(
    isDictionaryForm: false,
    subConditions: ['v5ss', 'v5sp'],
  ),
  'v5ss': ConditionSpec(),
  'v5sp': ConditionSpec(),
  'vk': ConditionSpec(isDictionaryForm: true),
  'vs': ConditionSpec(isDictionaryForm: true),
  'vz': ConditionSpec(isDictionaryForm: true),
  'adj-i': ConditionSpec(isDictionaryForm: true),
  '-ます': ConditionSpec(),
  '-ません': ConditionSpec(),
  '-て': ConditionSpec(),
  '-ば': ConditionSpec(),
  '-く': ConditionSpec(),
  '-た': ConditionSpec(),
  '-ん': ConditionSpec(),
  '-なさい': ConditionSpec(),
  '-ゃ': ConditionSpec(),
};

/// Yomitan `japaneseTransforms.transforms` (suffix + whole-word rules).
const List<TransformSpec> japaneseTransforms = [
  TransformSpec(
    id: '-ば',
    name: '-ば',
    rules: [
      InflectionRule.suffix('ければ', 'い', ['-ば'], ['adj-i']),
      InflectionRule.suffix('えば', 'う', ['-ば'], ['v5']),
      InflectionRule.suffix('へば', 'う', ['-ば'], ['v5']),
      InflectionRule.suffix('けば', 'く', ['-ば'], ['v5']),
      InflectionRule.suffix('げば', 'ぐ', ['-ば'], ['v5']),
      InflectionRule.suffix('せば', 'す', ['-ば'], ['v5']),
      InflectionRule.suffix('てば', 'つ', ['-ば'], ['v5']),
      InflectionRule.suffix('ねば', 'ぬ', ['-ば'], ['v5']),
      InflectionRule.suffix('べば', 'ぶ', ['-ば'], ['v5']),
      InflectionRule.suffix('めば', 'む', ['-ば'], ['v5']),
      InflectionRule.suffix('れば', 'る', ['-ば'], ['v1', 'v5', 'vk', 'vs', 'vz']),
      InflectionRule.suffix('れば', '', ['-ば'], ['-ます']),
    ],
  ),
  TransformSpec(
    id: '-ゃ',
    name: '-ゃ',
    rules: [
      InflectionRule.suffix('けりゃ', 'ければ', ['-ゃ'], ['-ば']),
      InflectionRule.suffix('きゃ', 'ければ', ['-ゃ'], ['-ば']),
      InflectionRule.suffix('や', 'えば', ['-ゃ'], ['-ば']),
      InflectionRule.suffix('きゃ', 'けば', ['-ゃ'], ['-ば']),
      InflectionRule.suffix('ぎゃ', 'げば', ['-ゃ'], ['-ば']),
      InflectionRule.suffix('しゃ', 'せば', ['-ゃ'], ['-ば']),
      InflectionRule.suffix('ちゃ', 'てば', ['-ゃ'], ['-ば']),
      InflectionRule.suffix('にゃ', 'ねば', ['-ゃ'], ['-ば']),
      InflectionRule.suffix('びゃ', 'べば', ['-ゃ'], ['-ば']),
      InflectionRule.suffix('みゃ', 'めば', ['-ゃ'], ['-ば']),
      InflectionRule.suffix('りゃ', 'れば', ['-ゃ'], ['-ば']),
    ],
  ),
  TransformSpec(
    id: '-ちゃ',
    name: '-ちゃ',
    rules: [
      InflectionRule.suffix('ちゃ', 'る', ['v5'], ['v1']),
      InflectionRule.suffix('いじゃ', 'ぐ', ['v5'], ['v5']),
      InflectionRule.suffix('いちゃ', 'く', ['v5'], ['v5']),
      InflectionRule.suffix('しちゃ', 'す', ['v5'], ['v5']),
      InflectionRule.suffix('っちゃ', 'う', ['v5'], ['v5']),
      InflectionRule.suffix('っちゃ', 'く', ['v5'], ['v5']),
      InflectionRule.suffix('っちゃ', 'つ', ['v5'], ['v5']),
      InflectionRule.suffix('っちゃ', 'る', ['v5'], ['v5']),
      InflectionRule.suffix('んじゃ', 'ぬ', ['v5'], ['v5']),
      InflectionRule.suffix('んじゃ', 'ぶ', ['v5'], ['v5']),
      InflectionRule.suffix('んじゃ', 'む', ['v5'], ['v5']),
      InflectionRule.suffix('じちゃ', 'ずる', ['v5'], ['vz']),
      InflectionRule.suffix('しちゃ', 'する', ['v5'], ['vs']),
      InflectionRule.suffix('為ちゃ', '為る', ['v5'], ['vs']),
      InflectionRule.suffix('きちゃ', 'くる', ['v5'], ['vk']),
      InflectionRule.suffix('来ちゃ', '来る', ['v5'], ['vk']),
      InflectionRule.suffix('來ちゃ', '來る', ['v5'], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-ちゃう',
    name: '-ちゃう',
    rules: [
      InflectionRule.suffix('ちゃう', 'る', ['v5'], ['v1']),
      InflectionRule.suffix('いじゃう', 'ぐ', ['v5'], ['v5']),
      InflectionRule.suffix('いちゃう', 'く', ['v5'], ['v5']),
      InflectionRule.suffix('しちゃう', 'す', ['v5'], ['v5']),
      InflectionRule.suffix('っちゃう', 'う', ['v5'], ['v5']),
      InflectionRule.suffix('っちゃう', 'く', ['v5'], ['v5']),
      InflectionRule.suffix('っちゃう', 'つ', ['v5'], ['v5']),
      InflectionRule.suffix('っちゃう', 'る', ['v5'], ['v5']),
      InflectionRule.suffix('んじゃう', 'ぬ', ['v5'], ['v5']),
      InflectionRule.suffix('んじゃう', 'ぶ', ['v5'], ['v5']),
      InflectionRule.suffix('んじゃう', 'む', ['v5'], ['v5']),
      InflectionRule.suffix('じちゃう', 'ずる', ['v5'], ['vz']),
      InflectionRule.suffix('しちゃう', 'する', ['v5'], ['vs']),
      InflectionRule.suffix('為ちゃう', '為る', ['v5'], ['vs']),
      InflectionRule.suffix('きちゃう', 'くる', ['v5'], ['vk']),
      InflectionRule.suffix('来ちゃう', '来る', ['v5'], ['vk']),
      InflectionRule.suffix('來ちゃう', '來る', ['v5'], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-ちまう',
    name: '-ちまう',
    rules: [
      InflectionRule.suffix('ちまう', 'る', ['v5'], ['v1']),
      InflectionRule.suffix('いじまう', 'ぐ', ['v5'], ['v5']),
      InflectionRule.suffix('いちまう', 'く', ['v5'], ['v5']),
      InflectionRule.suffix('しちまう', 'す', ['v5'], ['v5']),
      InflectionRule.suffix('っちまう', 'う', ['v5'], ['v5']),
      InflectionRule.suffix('っちまう', 'く', ['v5'], ['v5']),
      InflectionRule.suffix('っちまう', 'つ', ['v5'], ['v5']),
      InflectionRule.suffix('っちまう', 'る', ['v5'], ['v5']),
      InflectionRule.suffix('んじまう', 'ぬ', ['v5'], ['v5']),
      InflectionRule.suffix('んじまう', 'ぶ', ['v5'], ['v5']),
      InflectionRule.suffix('んじまう', 'む', ['v5'], ['v5']),
      InflectionRule.suffix('じちまう', 'ずる', ['v5'], ['vz']),
      InflectionRule.suffix('しちまう', 'する', ['v5'], ['vs']),
      InflectionRule.suffix('為ちまう', '為る', ['v5'], ['vs']),
      InflectionRule.suffix('きちまう', 'くる', ['v5'], ['vk']),
      InflectionRule.suffix('来ちまう', '来る', ['v5'], ['vk']),
      InflectionRule.suffix('來ちまう', '來る', ['v5'], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-しまう',
    name: '-しまう',
    rules: [
      InflectionRule.suffix('てしまう', 'て', ['v5'], ['-て']),
      InflectionRule.suffix('でしまう', 'で', ['v5'], ['-て']),
    ],
  ),
  TransformSpec(
    id: '-なさい',
    name: '-なさい',
    rules: [
      InflectionRule.suffix('なさい', 'る', ['-なさい'], ['v1']),
      InflectionRule.suffix('いなさい', 'う', ['-なさい'], ['v5']),
      InflectionRule.suffix('きなさい', 'く', ['-なさい'], ['v5']),
      InflectionRule.suffix('ぎなさい', 'ぐ', ['-なさい'], ['v5']),
      InflectionRule.suffix('しなさい', 'す', ['-なさい'], ['v5']),
      InflectionRule.suffix('ちなさい', 'つ', ['-なさい'], ['v5']),
      InflectionRule.suffix('になさい', 'ぬ', ['-なさい'], ['v5']),
      InflectionRule.suffix('びなさい', 'ぶ', ['-なさい'], ['v5']),
      InflectionRule.suffix('みなさい', 'む', ['-なさい'], ['v5']),
      InflectionRule.suffix('りなさい', 'る', ['-なさい'], ['v5']),
      InflectionRule.suffix('じなさい', 'ずる', ['-なさい'], ['vz']),
      InflectionRule.suffix('しなさい', 'する', ['-なさい'], ['vs']),
      InflectionRule.suffix('為なさい', '為る', ['-なさい'], ['vs']),
      InflectionRule.suffix('きなさい', 'くる', ['-なさい'], ['vk']),
      InflectionRule.suffix('来なさい', '来る', ['-なさい'], ['vk']),
      InflectionRule.suffix('來なさい', '來る', ['-なさい'], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-そう',
    name: '-そう',
    rules: [
      InflectionRule.suffix('そう', 'い', <String>[], ['adj-i']),
      InflectionRule.suffix('さう', 'い', <String>[], ['adj-i']),
      InflectionRule.suffix('そう', 'る', <String>[], ['v1']),
      InflectionRule.suffix('さう', 'る', <String>[], ['v1']),
      InflectionRule.suffix('いそう', 'う', <String>[], ['v5']),
      InflectionRule.suffix('ひさう', 'う', <String>[], ['v5']),
      InflectionRule.suffix('きそう', 'く', <String>[], ['v5']),
      InflectionRule.suffix('きさう', 'く', <String>[], ['v5']),
      InflectionRule.suffix('ぎそう', 'ぐ', <String>[], ['v5']),
      InflectionRule.suffix('ぎさう', 'ぐ', <String>[], ['v5']),
      InflectionRule.suffix('しそう', 'す', <String>[], ['v5']),
      InflectionRule.suffix('しさう', 'す', <String>[], ['v5']),
      InflectionRule.suffix('ちそう', 'つ', <String>[], ['v5']),
      InflectionRule.suffix('ちさう', 'つ', <String>[], ['v5']),
      InflectionRule.suffix('にそう', 'ぬ', <String>[], ['v5']),
      InflectionRule.suffix('にさう', 'ぬ', <String>[], ['v5']),
      InflectionRule.suffix('びそう', 'ぶ', <String>[], ['v5']),
      InflectionRule.suffix('びさう', 'ぶ', <String>[], ['v5']),
      InflectionRule.suffix('みそう', 'む', <String>[], ['v5']),
      InflectionRule.suffix('みさう', 'む', <String>[], ['v5']),
      InflectionRule.suffix('りそう', 'る', <String>[], ['v5']),
      InflectionRule.suffix('りさう', 'る', <String>[], ['v5']),
      InflectionRule.suffix('じそう', 'ずる', <String>[], ['vz']),
      InflectionRule.suffix('じさう', 'ずる', <String>[], ['vz']),
      InflectionRule.suffix('しそう', 'する', <String>[], ['vs']),
      InflectionRule.suffix('しさう', 'する', <String>[], ['vs']),
      InflectionRule.suffix('為そう', '為る', <String>[], ['vs']),
      InflectionRule.suffix('為さう', '為る', <String>[], ['vs']),
      InflectionRule.suffix('きそう', 'くる', <String>[], ['vk']),
      InflectionRule.suffix('きさう', 'くる', <String>[], ['vk']),
      InflectionRule.suffix('来そう', '来る', <String>[], ['vk']),
      InflectionRule.suffix('来さう', '来る', <String>[], ['vk']),
      InflectionRule.suffix('來そう', '來る', <String>[], ['vk']),
      InflectionRule.suffix('來さう', '來る', <String>[], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-すぎる',
    name: '-すぎる',
    rules: [
      InflectionRule.suffix('すぎる', 'い', ['v1'], ['adj-i']),
      InflectionRule.suffix('すぎる', 'る', ['v1'], ['v1']),
      InflectionRule.suffix('いすぎる', 'う', ['v1'], ['v5']),
      InflectionRule.suffix('きすぎる', 'く', ['v1'], ['v5']),
      InflectionRule.suffix('ぎすぎる', 'ぐ', ['v1'], ['v5']),
      InflectionRule.suffix('しすぎる', 'す', ['v1'], ['v5']),
      InflectionRule.suffix('ちすぎる', 'つ', ['v1'], ['v5']),
      InflectionRule.suffix('にすぎる', 'ぬ', ['v1'], ['v5']),
      InflectionRule.suffix('びすぎる', 'ぶ', ['v1'], ['v5']),
      InflectionRule.suffix('みすぎる', 'む', ['v1'], ['v5']),
      InflectionRule.suffix('りすぎる', 'る', ['v1'], ['v5']),
      InflectionRule.suffix('じすぎる', 'ずる', ['v1'], ['vz']),
      InflectionRule.suffix('しすぎる', 'する', ['v1'], ['vs']),
      InflectionRule.suffix('為すぎる', '為る', ['v1'], ['vs']),
      InflectionRule.suffix('きすぎる', 'くる', ['v1'], ['vk']),
      InflectionRule.suffix('来すぎる', '来る', ['v1'], ['vk']),
      InflectionRule.suffix('來すぎる', '來る', ['v1'], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-過ぎる',
    name: '-過ぎる',
    rules: [
      InflectionRule.suffix('過ぎる', 'い', ['v1'], ['adj-i']),
      InflectionRule.suffix('過ぎる', 'る', ['v1'], ['v1']),
      InflectionRule.suffix('い過ぎる', 'う', ['v1'], ['v5']),
      InflectionRule.suffix('き過ぎる', 'く', ['v1'], ['v5']),
      InflectionRule.suffix('ぎ過ぎる', 'ぐ', ['v1'], ['v5']),
      InflectionRule.suffix('し過ぎる', 'す', ['v1'], ['v5']),
      InflectionRule.suffix('ち過ぎる', 'つ', ['v1'], ['v5']),
      InflectionRule.suffix('に過ぎる', 'ぬ', ['v1'], ['v5']),
      InflectionRule.suffix('び過ぎる', 'ぶ', ['v1'], ['v5']),
      InflectionRule.suffix('み過ぎる', 'む', ['v1'], ['v5']),
      InflectionRule.suffix('り過ぎる', 'る', ['v1'], ['v5']),
      InflectionRule.suffix('じ過ぎる', 'ずる', ['v1'], ['vz']),
      InflectionRule.suffix('し過ぎる', 'する', ['v1'], ['vs']),
      InflectionRule.suffix('為過ぎる', '為る', ['v1'], ['vs']),
      InflectionRule.suffix('き過ぎる', 'くる', ['v1'], ['vk']),
      InflectionRule.suffix('来過ぎる', '来る', ['v1'], ['vk']),
      InflectionRule.suffix('來過ぎる', '來る', ['v1'], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-たい',
    name: '-たい',
    rules: [
      InflectionRule.suffix('たい', 'る', ['adj-i'], ['v1']),
      InflectionRule.suffix('いたい', 'う', ['adj-i'], ['v5']),
      InflectionRule.suffix('きたい', 'く', ['adj-i'], ['v5']),
      InflectionRule.suffix('ぎたい', 'ぐ', ['adj-i'], ['v5']),
      InflectionRule.suffix('したい', 'す', ['adj-i'], ['v5']),
      InflectionRule.suffix('ちたい', 'つ', ['adj-i'], ['v5']),
      InflectionRule.suffix('にたい', 'ぬ', ['adj-i'], ['v5']),
      InflectionRule.suffix('びたい', 'ぶ', ['adj-i'], ['v5']),
      InflectionRule.suffix('みたい', 'む', ['adj-i'], ['v5']),
      InflectionRule.suffix('りたい', 'る', ['adj-i'], ['v5']),
      InflectionRule.suffix('じたい', 'ずる', ['adj-i'], ['vz']),
      InflectionRule.suffix('したい', 'する', ['adj-i'], ['vs']),
      InflectionRule.suffix('為たい', '為る', ['adj-i'], ['vs']),
      InflectionRule.suffix('きたい', 'くる', ['adj-i'], ['vk']),
      InflectionRule.suffix('来たい', '来る', ['adj-i'], ['vk']),
      InflectionRule.suffix('來たい', '來る', ['adj-i'], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-たら',
    name: '-たら',
    rules: [
      InflectionRule.suffix('かったら', 'い', <String>[], ['adj-i']),
      InflectionRule.suffix('たら', 'る', <String>[], ['v1']),
      InflectionRule.suffix('いたら', 'く', <String>[], ['v5']),
      InflectionRule.suffix('いだら', 'ぐ', <String>[], ['v5']),
      InflectionRule.suffix('したら', 'す', <String>[], ['v5']),
      InflectionRule.suffix('ったら', 'う', <String>[], ['v5']),
      InflectionRule.suffix('ったら', 'つ', <String>[], ['v5']),
      InflectionRule.suffix('ったら', 'る', <String>[], ['v5']),
      InflectionRule.suffix('んだら', 'ぬ', <String>[], ['v5']),
      InflectionRule.suffix('んだら', 'ぶ', <String>[], ['v5']),
      InflectionRule.suffix('んだら', 'む', <String>[], ['v5']),
      InflectionRule.suffix('じたら', 'ずる', <String>[], ['vz']),
      InflectionRule.suffix('したら', 'する', <String>[], ['vs']),
      InflectionRule.suffix('為たら', '為る', <String>[], ['vs']),
      InflectionRule.suffix('きたら', 'くる', <String>[], ['vk']),
      InflectionRule.suffix('来たら', '来る', <String>[], ['vk']),
      InflectionRule.suffix('來たら', '來る', <String>[], ['vk']),
      InflectionRule.suffix('いったら', 'いく', <String>[], ['v5']),
      InflectionRule.suffix('行ったら', '行く', <String>[], ['v5']),
      InflectionRule.suffix('逝ったら', '逝く', <String>[], ['v5']),
      InflectionRule.suffix('往ったら', '往く', <String>[], ['v5']),
      InflectionRule.suffix('こうたら', 'こう', <String>[], ['v5']),
      InflectionRule.suffix('とうたら', 'とう', <String>[], ['v5']),
      InflectionRule.suffix('請うたら', '請う', <String>[], ['v5']),
      InflectionRule.suffix('乞うたら', '乞う', <String>[], ['v5']),
      InflectionRule.suffix('恋うたら', '恋う', <String>[], ['v5']),
      InflectionRule.suffix('問うたら', '問う', <String>[], ['v5']),
      InflectionRule.suffix('訪うたら', '訪う', <String>[], ['v5']),
      InflectionRule.suffix('宣うたら', '宣う', <String>[], ['v5']),
      InflectionRule.suffix('曰うたら', '曰う', <String>[], ['v5']),
      InflectionRule.suffix('給うたら', '給う', <String>[], ['v5']),
      InflectionRule.suffix('賜うたら', '賜う', <String>[], ['v5']),
      InflectionRule.suffix('揺蕩うたら', '揺蕩う', <String>[], ['v5']),
      InflectionRule.suffix('のたもうたら', 'のたまう', <String>[], ['v5']),
      InflectionRule.suffix('たもうたら', 'たまう', <String>[], ['v5']),
      InflectionRule.suffix('たゆとうたら', 'たゆたう', <String>[], ['v5']),
      InflectionRule.suffix('ましたら', 'ます', <String>[], ['-ます']),
    ],
  ),
  TransformSpec(
    id: '-たり',
    name: '-たり',
    rules: [
      InflectionRule.suffix('かったり', 'い', <String>[], ['adj-i']),
      InflectionRule.suffix('たり', 'る', <String>[], ['v1']),
      InflectionRule.suffix('いたり', 'く', <String>[], ['v5']),
      InflectionRule.suffix('いだり', 'ぐ', <String>[], ['v5']),
      InflectionRule.suffix('したり', 'す', <String>[], ['v5']),
      InflectionRule.suffix('ったり', 'う', <String>[], ['v5']),
      InflectionRule.suffix('ったり', 'つ', <String>[], ['v5']),
      InflectionRule.suffix('ったり', 'る', <String>[], ['v5']),
      InflectionRule.suffix('んだり', 'ぬ', <String>[], ['v5']),
      InflectionRule.suffix('んだり', 'ぶ', <String>[], ['v5']),
      InflectionRule.suffix('んだり', 'む', <String>[], ['v5']),
      InflectionRule.suffix('じたり', 'ずる', <String>[], ['vz']),
      InflectionRule.suffix('したり', 'する', <String>[], ['vs']),
      InflectionRule.suffix('為たり', '為る', <String>[], ['vs']),
      InflectionRule.suffix('きたり', 'くる', <String>[], ['vk']),
      InflectionRule.suffix('来たり', '来る', <String>[], ['vk']),
      InflectionRule.suffix('來たり', '來る', <String>[], ['vk']),
      InflectionRule.suffix('いったり', 'いく', <String>[], ['v5']),
      InflectionRule.suffix('行ったり', '行く', <String>[], ['v5']),
      InflectionRule.suffix('逝ったり', '逝く', <String>[], ['v5']),
      InflectionRule.suffix('往ったり', '往く', <String>[], ['v5']),
      InflectionRule.suffix('こうたり', 'こう', <String>[], ['v5']),
      InflectionRule.suffix('とうたり', 'とう', <String>[], ['v5']),
      InflectionRule.suffix('請うたり', '請う', <String>[], ['v5']),
      InflectionRule.suffix('乞うたり', '乞う', <String>[], ['v5']),
      InflectionRule.suffix('恋うたり', '恋う', <String>[], ['v5']),
      InflectionRule.suffix('問うたり', '問う', <String>[], ['v5']),
      InflectionRule.suffix('訪うたり', '訪う', <String>[], ['v5']),
      InflectionRule.suffix('宣うたり', '宣う', <String>[], ['v5']),
      InflectionRule.suffix('曰うたり', '曰う', <String>[], ['v5']),
      InflectionRule.suffix('給うたり', '給う', <String>[], ['v5']),
      InflectionRule.suffix('賜うたり', '賜う', <String>[], ['v5']),
      InflectionRule.suffix('揺蕩うたり', '揺蕩う', <String>[], ['v5']),
      InflectionRule.suffix('のたもうたり', 'のたまう', <String>[], ['v5']),
      InflectionRule.suffix('たもうたり', 'たまう', <String>[], ['v5']),
      InflectionRule.suffix('たゆとうたり', 'たゆたう', <String>[], ['v5']),
    ],
  ),
  TransformSpec(
    id: '-て',
    name: '-て',
    rules: [
      InflectionRule.suffix('くて', 'い', ['-て'], ['adj-i']),
      InflectionRule.suffix('て', 'る', ['-て'], ['v1']),
      InflectionRule.suffix('いて', 'く', ['-て'], ['v5']),
      InflectionRule.suffix('いで', 'ぐ', ['-て'], ['v5']),
      InflectionRule.suffix('して', 'す', ['-て'], ['v5']),
      InflectionRule.suffix('って', 'う', ['-て'], ['v5']),
      InflectionRule.suffix('って', 'つ', ['-て'], ['v5']),
      InflectionRule.suffix('って', 'る', ['-て'], ['v5']),
      InflectionRule.suffix('んで', 'ぬ', ['-て'], ['v5']),
      InflectionRule.suffix('んで', 'ぶ', ['-て'], ['v5']),
      InflectionRule.suffix('んで', 'む', ['-て'], ['v5']),
      InflectionRule.suffix('じて', 'ずる', ['-て'], ['vz']),
      InflectionRule.suffix('して', 'する', ['-て'], ['vs']),
      InflectionRule.suffix('為て', '為る', ['-て'], ['vs']),
      InflectionRule.suffix('きて', 'くる', ['-て'], ['vk']),
      InflectionRule.suffix('来て', '来る', ['-て'], ['vk']),
      InflectionRule.suffix('來て', '來る', ['-て'], ['vk']),
      InflectionRule.suffix('いって', 'いく', ['-て'], ['v5']),
      InflectionRule.suffix('行って', '行く', ['-て'], ['v5']),
      InflectionRule.suffix('逝って', '逝く', ['-て'], ['v5']),
      InflectionRule.suffix('往って', '往く', ['-て'], ['v5']),
      InflectionRule.suffix('こうて', 'こう', ['-て'], ['v5']),
      InflectionRule.suffix('とうて', 'とう', ['-て'], ['v5']),
      InflectionRule.suffix('請うて', '請う', ['-て'], ['v5']),
      InflectionRule.suffix('乞うて', '乞う', ['-て'], ['v5']),
      InflectionRule.suffix('恋うて', '恋う', ['-て'], ['v5']),
      InflectionRule.suffix('問うて', '問う', ['-て'], ['v5']),
      InflectionRule.suffix('訪うて', '訪う', ['-て'], ['v5']),
      InflectionRule.suffix('宣うて', '宣う', ['-て'], ['v5']),
      InflectionRule.suffix('曰うて', '曰う', ['-て'], ['v5']),
      InflectionRule.suffix('給うて', '給う', ['-て'], ['v5']),
      InflectionRule.suffix('賜うて', '賜う', ['-て'], ['v5']),
      InflectionRule.suffix('揺蕩うて', '揺蕩う', ['-て'], ['v5']),
      InflectionRule.suffix('のたもうて', 'のたまう', ['-て'], ['v5']),
      InflectionRule.suffix('たもうて', 'たまう', ['-て'], ['v5']),
      InflectionRule.suffix('たゆとうて', 'たゆたう', ['-て'], ['v5']),
      InflectionRule.suffix('まして', 'ます', <String>[], ['-ます']),
    ],
  ),
  TransformSpec(
    id: '-ず',
    name: '-ず',
    rules: [
      InflectionRule.suffix('ず', 'る', <String>[], ['v1']),
      InflectionRule.suffix('かず', 'く', <String>[], ['v5']),
      InflectionRule.suffix('がず', 'ぐ', <String>[], ['v5']),
      InflectionRule.suffix('さず', 'す', <String>[], ['v5']),
      InflectionRule.suffix('たず', 'つ', <String>[], ['v5']),
      InflectionRule.suffix('なず', 'ぬ', <String>[], ['v5']),
      InflectionRule.suffix('ばず', 'ぶ', <String>[], ['v5']),
      InflectionRule.suffix('まず', 'む', <String>[], ['v5']),
      InflectionRule.suffix('らず', 'る', <String>[], ['v5']),
      InflectionRule.suffix('わず', 'う', <String>[], ['v5']),
      InflectionRule.suffix('はず', 'う', <String>[], ['v5']),
      InflectionRule.suffix('ぜず', 'ずる', <String>[], ['vz']),
      InflectionRule.suffix('せず', 'する', <String>[], ['vs']),
      InflectionRule.suffix('為ず', '為る', <String>[], ['vs']),
      InflectionRule.suffix('こず', 'くる', <String>[], ['vk']),
      InflectionRule.suffix('来ず', '来る', <String>[], ['vk']),
      InflectionRule.suffix('來ず', '來る', <String>[], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-ぬ',
    name: '-ぬ',
    rules: [
      InflectionRule.suffix('ぬ', 'る', <String>[], ['v1']),
      InflectionRule.suffix('かぬ', 'く', <String>[], ['v5']),
      InflectionRule.suffix('がぬ', 'ぐ', <String>[], ['v5']),
      InflectionRule.suffix('さぬ', 'す', <String>[], ['v5']),
      InflectionRule.suffix('たぬ', 'つ', <String>[], ['v5']),
      InflectionRule.suffix('なぬ', 'ぬ', <String>[], ['v5']),
      InflectionRule.suffix('ばぬ', 'ぶ', <String>[], ['v5']),
      InflectionRule.suffix('まぬ', 'む', <String>[], ['v5']),
      InflectionRule.suffix('らぬ', 'る', <String>[], ['v5']),
      InflectionRule.suffix('わぬ', 'う', <String>[], ['v5']),
      InflectionRule.suffix('はぬ', 'う', <String>[], ['v5']),
      InflectionRule.suffix('ぜぬ', 'ずる', <String>[], ['vz']),
      InflectionRule.suffix('せぬ', 'する', <String>[], ['vs']),
      InflectionRule.suffix('為ぬ', '為る', <String>[], ['vs']),
      InflectionRule.suffix('こぬ', 'くる', <String>[], ['vk']),
      InflectionRule.suffix('来ぬ', '来る', <String>[], ['vk']),
      InflectionRule.suffix('來ぬ', '來る', <String>[], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-ん',
    name: '-ん',
    rules: [
      InflectionRule.suffix('ん', 'る', ['-ん'], ['v1']),
      InflectionRule.suffix('かん', 'く', ['-ん'], ['v5']),
      InflectionRule.suffix('がん', 'ぐ', ['-ん'], ['v5']),
      InflectionRule.suffix('さん', 'す', ['-ん'], ['v5']),
      InflectionRule.suffix('たん', 'つ', ['-ん'], ['v5']),
      InflectionRule.suffix('なん', 'ぬ', ['-ん'], ['v5']),
      InflectionRule.suffix('ばん', 'ぶ', ['-ん'], ['v5']),
      InflectionRule.suffix('まん', 'む', ['-ん'], ['v5']),
      InflectionRule.suffix('らん', 'る', ['-ん'], ['v5']),
      InflectionRule.suffix('わん', 'う', ['-ん'], ['v5']),
      InflectionRule.suffix('はん', 'う', ['-ん'], ['v5']),
      InflectionRule.suffix('ぜん', 'ずる', ['-ん'], ['vz']),
      InflectionRule.suffix('せん', 'する', ['-ん'], ['vs']),
      InflectionRule.suffix('為ん', '為る', ['-ん'], ['vs']),
      InflectionRule.suffix('こん', 'くる', ['-ん'], ['vk']),
      InflectionRule.suffix('来ん', '来る', ['-ん'], ['vk']),
      InflectionRule.suffix('來ん', '來る', ['-ん'], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-んばかり',
    name: '-んばかり',
    rules: [
      InflectionRule.suffix('んばかり', 'る', <String>[], ['v1']),
      InflectionRule.suffix('かんばかり', 'く', <String>[], ['v5']),
      InflectionRule.suffix('がんばかり', 'ぐ', <String>[], ['v5']),
      InflectionRule.suffix('さんばかり', 'す', <String>[], ['v5']),
      InflectionRule.suffix('たんばかり', 'つ', <String>[], ['v5']),
      InflectionRule.suffix('なんばかり', 'ぬ', <String>[], ['v5']),
      InflectionRule.suffix('ばんばかり', 'ぶ', <String>[], ['v5']),
      InflectionRule.suffix('まんばかり', 'む', <String>[], ['v5']),
      InflectionRule.suffix('らんばかり', 'る', <String>[], ['v5']),
      InflectionRule.suffix('わんばかり', 'う', <String>[], ['v5']),
      InflectionRule.suffix('はんばかり', 'う', <String>[], ['v5']),
      InflectionRule.suffix('ぜんばかり', 'ずる', <String>[], ['vz']),
      InflectionRule.suffix('せんばかり', 'する', <String>[], ['vs']),
      InflectionRule.suffix('為んばかり', '為る', <String>[], ['vs']),
      InflectionRule.suffix('こんばかり', 'くる', <String>[], ['vk']),
      InflectionRule.suffix('来んばかり', '来る', <String>[], ['vk']),
      InflectionRule.suffix('來んばかり', '來る', <String>[], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-んとする',
    name: '-んとする',
    rules: [
      InflectionRule.suffix('んとする', 'る', ['vs'], ['v1']),
      InflectionRule.suffix('かんとする', 'く', ['vs'], ['v5']),
      InflectionRule.suffix('がんとする', 'ぐ', ['vs'], ['v5']),
      InflectionRule.suffix('さんとする', 'す', ['vs'], ['v5']),
      InflectionRule.suffix('たんとする', 'つ', ['vs'], ['v5']),
      InflectionRule.suffix('なんとする', 'ぬ', ['vs'], ['v5']),
      InflectionRule.suffix('ばんとする', 'ぶ', ['vs'], ['v5']),
      InflectionRule.suffix('まんとする', 'む', ['vs'], ['v5']),
      InflectionRule.suffix('らんとする', 'る', ['vs'], ['v5']),
      InflectionRule.suffix('わんとする', 'う', ['vs'], ['v5']),
      InflectionRule.suffix('はんとする', 'う', ['vs'], ['v5']),
      InflectionRule.suffix('ぜんとする', 'ずる', ['vs'], ['vz']),
      InflectionRule.suffix('せんとする', 'する', ['vs'], ['vs']),
      InflectionRule.suffix('為んとする', '為る', ['vs'], ['vs']),
      InflectionRule.suffix('こんとする', 'くる', ['vs'], ['vk']),
      InflectionRule.suffix('来んとする', '来る', ['vs'], ['vk']),
      InflectionRule.suffix('來んとする', '來る', ['vs'], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-む',
    name: '-む',
    rules: [
      InflectionRule.suffix('む', 'る', <String>[], ['v1']),
      InflectionRule.suffix('かむ', 'く', <String>[], ['v5']),
      InflectionRule.suffix('がむ', 'ぐ', <String>[], ['v5']),
      InflectionRule.suffix('さむ', 'す', <String>[], ['v5']),
      InflectionRule.suffix('たむ', 'つ', <String>[], ['v5']),
      InflectionRule.suffix('なむ', 'ぬ', <String>[], ['v5']),
      InflectionRule.suffix('ばむ', 'ぶ', <String>[], ['v5']),
      InflectionRule.suffix('まむ', 'む', <String>[], ['v5']),
      InflectionRule.suffix('らむ', 'る', <String>[], ['v5']),
      InflectionRule.suffix('わむ', 'う', <String>[], ['v5']),
      InflectionRule.suffix('はむ', 'う', <String>[], ['v5']),
      InflectionRule.suffix('ぜむ', 'ずる', <String>[], ['vz']),
      InflectionRule.suffix('せむ', 'する', <String>[], ['vs']),
      InflectionRule.suffix('為む', '為る', <String>[], ['vs']),
      InflectionRule.suffix('こむ', 'くる', <String>[], ['vk']),
      InflectionRule.suffix('来む', '来る', <String>[], ['vk']),
      InflectionRule.suffix('來む', '來る', <String>[], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-ざる',
    name: '-ざる',
    rules: [
      InflectionRule.suffix('ざる', 'る', <String>[], ['v1']),
      InflectionRule.suffix('かざる', 'く', <String>[], ['v5']),
      InflectionRule.suffix('がざる', 'ぐ', <String>[], ['v5']),
      InflectionRule.suffix('さざる', 'す', <String>[], ['v5']),
      InflectionRule.suffix('たざる', 'つ', <String>[], ['v5']),
      InflectionRule.suffix('なざる', 'ぬ', <String>[], ['v5']),
      InflectionRule.suffix('ばざる', 'ぶ', <String>[], ['v5']),
      InflectionRule.suffix('まざる', 'む', <String>[], ['v5']),
      InflectionRule.suffix('らざる', 'る', <String>[], ['v5']),
      InflectionRule.suffix('わざる', 'う', <String>[], ['v5']),
      InflectionRule.suffix('はざる', 'う', <String>[], ['v5']),
      InflectionRule.suffix('ぜざる', 'ずる', <String>[], ['vz']),
      InflectionRule.suffix('せざる', 'する', <String>[], ['vs']),
      InflectionRule.suffix('為ざる', '為る', <String>[], ['vs']),
      InflectionRule.suffix('こざる', 'くる', <String>[], ['vk']),
      InflectionRule.suffix('来ざる', '来る', <String>[], ['vk']),
      InflectionRule.suffix('來ざる', '來る', <String>[], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-ねば',
    name: '-ねば',
    rules: [
      InflectionRule.suffix('ねば', 'る', ['-ば'], ['v1']),
      InflectionRule.suffix('かねば', 'く', ['-ば'], ['v5']),
      InflectionRule.suffix('がねば', 'ぐ', ['-ば'], ['v5']),
      InflectionRule.suffix('さねば', 'す', ['-ば'], ['v5']),
      InflectionRule.suffix('たねば', 'つ', ['-ば'], ['v5']),
      InflectionRule.suffix('なねば', 'ぬ', ['-ば'], ['v5']),
      InflectionRule.suffix('ばねば', 'ぶ', ['-ば'], ['v5']),
      InflectionRule.suffix('まねば', 'む', ['-ば'], ['v5']),
      InflectionRule.suffix('らねば', 'る', ['-ば'], ['v5']),
      InflectionRule.suffix('わねば', 'う', ['-ば'], ['v5']),
      InflectionRule.suffix('はねば', 'う', ['-ば'], ['v5']),
      InflectionRule.suffix('ぜねば', 'ずる', ['-ば'], ['vz']),
      InflectionRule.suffix('せねば', 'する', ['-ば'], ['vs']),
      InflectionRule.suffix('為ねば', '為る', ['-ば'], ['vs']),
      InflectionRule.suffix('こねば', 'くる', ['-ば'], ['vk']),
      InflectionRule.suffix('来ねば', '来る', ['-ば'], ['vk']),
      InflectionRule.suffix('來ねば', '來る', ['-ば'], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-く',
    name: '-く',
    rules: [
      InflectionRule.suffix('く', 'い', ['-く'], ['adj-i']),
    ],
  ),
  TransformSpec(
    id: 'causative',
    name: 'causative',
    rules: [
      InflectionRule.suffix('させる', 'る', ['v1'], ['v1']),
      InflectionRule.suffix('かせる', 'く', ['v1'], ['v5']),
      InflectionRule.suffix('がせる', 'ぐ', ['v1'], ['v5']),
      InflectionRule.suffix('させる', 'す', ['v1'], ['v5']),
      InflectionRule.suffix('たせる', 'つ', ['v1'], ['v5']),
      InflectionRule.suffix('なせる', 'ぬ', ['v1'], ['v5']),
      InflectionRule.suffix('ばせる', 'ぶ', ['v1'], ['v5']),
      InflectionRule.suffix('ませる', 'む', ['v1'], ['v5']),
      InflectionRule.suffix('らせる', 'る', ['v1'], ['v5']),
      InflectionRule.suffix('わせる', 'う', ['v1'], ['v5']),
      InflectionRule.suffix('はせる', 'う', ['v1'], ['v5']),
      InflectionRule.suffix('じさせる', 'ずる', ['v1'], ['vz']),
      InflectionRule.suffix('ぜさせる', 'ずる', ['v1'], ['vz']),
      InflectionRule.suffix('させる', 'する', ['v1'], ['vs']),
      InflectionRule.suffix('為せる', '為る', ['v1'], ['vs']),
      InflectionRule.suffix('せさせる', 'する', ['v1'], ['vs']),
      InflectionRule.suffix('為させる', '為る', ['v1'], ['vs']),
      InflectionRule.suffix('こさせる', 'くる', ['v1'], ['vk']),
      InflectionRule.suffix('来させる', '来る', ['v1'], ['vk']),
      InflectionRule.suffix('來させる', '來る', ['v1'], ['vk']),
    ],
  ),
  TransformSpec(
    id: 'short causative',
    name: 'short causative',
    rules: [
      InflectionRule.suffix('さす', 'る', ['v5ss'], ['v1']),
      InflectionRule.suffix('かす', 'く', ['v5sp'], ['v5']),
      InflectionRule.suffix('がす', 'ぐ', ['v5sp'], ['v5']),
      InflectionRule.suffix('さす', 'す', ['v5ss'], ['v5']),
      InflectionRule.suffix('たす', 'つ', ['v5sp'], ['v5']),
      InflectionRule.suffix('なす', 'ぬ', ['v5sp'], ['v5']),
      InflectionRule.suffix('ばす', 'ぶ', ['v5sp'], ['v5']),
      InflectionRule.suffix('ます', 'む', ['v5sp'], ['v5']),
      InflectionRule.suffix('らす', 'る', ['v5sp'], ['v5']),
      InflectionRule.suffix('わす', 'う', ['v5sp'], ['v5']),
      InflectionRule.suffix('はす', 'う', ['v5sp'], ['v5']),
      InflectionRule.suffix('じさす', 'ずる', ['v5ss'], ['vz']),
      InflectionRule.suffix('ぜさす', 'ずる', ['v5ss'], ['vz']),
      InflectionRule.suffix('さす', 'する', ['v5ss'], ['vs']),
      InflectionRule.suffix('為す', '為る', ['v5ss'], ['vs']),
      InflectionRule.suffix('こさす', 'くる', ['v5ss'], ['vk']),
      InflectionRule.suffix('来さす', '来る', ['v5ss'], ['vk']),
      InflectionRule.suffix('來さす', '來る', ['v5ss'], ['vk']),
    ],
  ),
  TransformSpec(
    id: 'imperative',
    name: 'imperative',
    rules: [
      InflectionRule.suffix('ろ', 'る', <String>[], ['v1']),
      InflectionRule.suffix('よ', 'る', <String>[], ['v1']),
      InflectionRule.suffix('え', 'う', <String>[], ['v5']),
      InflectionRule.suffix('へ', 'う', <String>[], ['v5']),
      InflectionRule.suffix('け', 'く', <String>[], ['v5']),
      InflectionRule.suffix('げ', 'ぐ', <String>[], ['v5']),
      InflectionRule.suffix('せ', 'す', <String>[], ['v5']),
      InflectionRule.suffix('て', 'つ', <String>[], ['v5']),
      InflectionRule.suffix('ね', 'ぬ', <String>[], ['v5']),
      InflectionRule.suffix('べ', 'ぶ', <String>[], ['v5']),
      InflectionRule.suffix('め', 'む', <String>[], ['v5']),
      InflectionRule.suffix('れ', 'る', <String>[], ['v5']),
      InflectionRule.suffix('じろ', 'ずる', <String>[], ['vz']),
      InflectionRule.suffix('ぜよ', 'ずる', <String>[], ['vz']),
      InflectionRule.suffix('しろ', 'する', <String>[], ['vs']),
      InflectionRule.suffix('せよ', 'する', <String>[], ['vs']),
      InflectionRule.suffix('為ろ', '為る', <String>[], ['vs']),
      InflectionRule.suffix('為よ', '為る', <String>[], ['vs']),
      InflectionRule.suffix('こい', 'くる', <String>[], ['vk']),
      InflectionRule.suffix('来い', '来る', <String>[], ['vk']),
      InflectionRule.suffix('來い', '來る', <String>[], ['vk']),
    ],
  ),
  TransformSpec(
    id: 'continuative',
    name: 'continuative',
    rules: [
      InflectionRule.suffix('い', 'いる', <String>[], ['v1d']),
      InflectionRule.suffix('え', 'える', <String>[], ['v1d']),
      InflectionRule.suffix('き', 'きる', <String>[], ['v1d']),
      InflectionRule.suffix('ぎ', 'ぎる', <String>[], ['v1d']),
      InflectionRule.suffix('け', 'ける', <String>[], ['v1d']),
      InflectionRule.suffix('げ', 'げる', <String>[], ['v1d']),
      InflectionRule.suffix('じ', 'じる', <String>[], ['v1d']),
      InflectionRule.suffix('せ', 'せる', <String>[], ['v1d']),
      InflectionRule.suffix('ぜ', 'ぜる', <String>[], ['v1d']),
      InflectionRule.suffix('ち', 'ちる', <String>[], ['v1d']),
      InflectionRule.suffix('て', 'てる', <String>[], ['v1d']),
      InflectionRule.suffix('で', 'でる', <String>[], ['v1d']),
      InflectionRule.suffix('に', 'にる', <String>[], ['v1d']),
      InflectionRule.suffix('ね', 'ねる', <String>[], ['v1d']),
      InflectionRule.suffix('ひ', 'ひる', <String>[], ['v1d']),
      InflectionRule.suffix('び', 'びる', <String>[], ['v1d']),
      InflectionRule.suffix('へ', 'へる', <String>[], ['v1d']),
      InflectionRule.suffix('べ', 'べる', <String>[], ['v1d']),
      InflectionRule.suffix('み', 'みる', <String>[], ['v1d']),
      InflectionRule.suffix('め', 'める', <String>[], ['v1d']),
      InflectionRule.suffix('り', 'りる', <String>[], ['v1d']),
      InflectionRule.suffix('れ', 'れる', <String>[], ['v1d']),
      InflectionRule.suffix('い', 'う', <String>[], ['v5']),
      InflectionRule.suffix('ひ', 'う', <String>[], ['v5']),
      InflectionRule.suffix('き', 'く', <String>[], ['v5']),
      InflectionRule.suffix('ぎ', 'ぐ', <String>[], ['v5']),
      InflectionRule.suffix('し', 'す', <String>[], ['v5']),
      InflectionRule.suffix('ち', 'つ', <String>[], ['v5']),
      InflectionRule.suffix('に', 'ぬ', <String>[], ['v5']),
      InflectionRule.suffix('び', 'ぶ', <String>[], ['v5']),
      InflectionRule.suffix('み', 'む', <String>[], ['v5']),
      InflectionRule.suffix('り', 'る', <String>[], ['v5']),
      InflectionRule.suffix('き', 'くる', <String>[], ['vk']),
      InflectionRule.suffix('し', 'する', <String>[], ['vs']),
      InflectionRule.suffix('来', '来る', <String>[], ['vk']),
      InflectionRule.suffix('來', '來る', <String>[], ['vk']),
    ],
  ),
  TransformSpec(
    id: 'negative',
    name: 'negative',
    rules: [
      InflectionRule.suffix('くない', 'い', ['adj-i'], ['adj-i']),
      InflectionRule.suffix('ない', 'る', ['adj-i'], ['v1']),
      InflectionRule.suffix('かない', 'く', ['adj-i'], ['v5']),
      InflectionRule.suffix('がない', 'ぐ', ['adj-i'], ['v5']),
      InflectionRule.suffix('さない', 'す', ['adj-i'], ['v5']),
      InflectionRule.suffix('たない', 'つ', ['adj-i'], ['v5']),
      InflectionRule.suffix('なない', 'ぬ', ['adj-i'], ['v5']),
      InflectionRule.suffix('ばない', 'ぶ', ['adj-i'], ['v5']),
      InflectionRule.suffix('まない', 'む', ['adj-i'], ['v5']),
      InflectionRule.suffix('らない', 'る', ['adj-i'], ['v5']),
      InflectionRule.suffix('わない', 'う', ['adj-i'], ['v5']),
      InflectionRule.suffix('はない', 'う', ['adj-i'], ['v5']),
      InflectionRule.suffix('じない', 'ずる', ['adj-i'], ['vz']),
      InflectionRule.suffix('しない', 'する', ['adj-i'], ['vs']),
      InflectionRule.suffix('為ない', '為る', ['adj-i'], ['vs']),
      InflectionRule.suffix('こない', 'くる', ['adj-i'], ['vk']),
      InflectionRule.suffix('来ない', '来る', ['adj-i'], ['vk']),
      InflectionRule.suffix('來ない', '來る', ['adj-i'], ['vk']),
      InflectionRule.suffix('ません', 'ます', ['-ません'], ['-ます']),
    ],
  ),
  TransformSpec(
    id: '-さ',
    name: '-さ',
    rules: [
      InflectionRule.suffix('さ', 'い', <String>[], ['adj-i']),
    ],
  ),
  TransformSpec(
    id: 'passive',
    name: 'passive',
    rules: [
      InflectionRule.suffix('かれる', 'く', ['v1'], ['v5']),
      InflectionRule.suffix('がれる', 'ぐ', ['v1'], ['v5']),
      InflectionRule.suffix('される', 'す', ['v1'], ['v5d', 'v5sp']),
      InflectionRule.suffix('たれる', 'つ', ['v1'], ['v5']),
      InflectionRule.suffix('なれる', 'ぬ', ['v1'], ['v5']),
      InflectionRule.suffix('ばれる', 'ぶ', ['v1'], ['v5']),
      InflectionRule.suffix('まれる', 'む', ['v1'], ['v5']),
      InflectionRule.suffix('われる', 'う', ['v1'], ['v5']),
      InflectionRule.suffix('はれる', 'う', ['v1'], ['v5']),
      InflectionRule.suffix('られる', 'る', ['v1'], ['v5']),
      InflectionRule.suffix('じされる', 'ずる', ['v1'], ['vz']),
      InflectionRule.suffix('ぜされる', 'ずる', ['v1'], ['vz']),
      InflectionRule.suffix('される', 'する', ['v1'], ['vs']),
      InflectionRule.suffix('為れる', '為る', ['v1'], ['vs']),
      InflectionRule.suffix('こられる', 'くる', ['v1'], ['vk']),
      InflectionRule.suffix('来られる', '来る', ['v1'], ['vk']),
      InflectionRule.suffix('來られる', '來る', ['v1'], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-た',
    name: '-た',
    rules: [
      InflectionRule.suffix('かった', 'い', ['-た'], ['adj-i']),
      InflectionRule.suffix('た', 'る', ['-た'], ['v1']),
      InflectionRule.suffix('いた', 'く', ['-た'], ['v5']),
      InflectionRule.suffix('いだ', 'ぐ', ['-た'], ['v5']),
      InflectionRule.suffix('した', 'す', ['-た'], ['v5']),
      InflectionRule.suffix('った', 'う', ['-た'], ['v5']),
      InflectionRule.suffix('った', 'つ', ['-た'], ['v5']),
      InflectionRule.suffix('った', 'る', ['-た'], ['v5']),
      InflectionRule.suffix('んだ', 'ぬ', ['-た'], ['v5']),
      InflectionRule.suffix('んだ', 'ぶ', ['-た'], ['v5']),
      InflectionRule.suffix('んだ', 'む', ['-た'], ['v5']),
      InflectionRule.suffix('じた', 'ずる', ['-た'], ['vz']),
      InflectionRule.suffix('した', 'する', ['-た'], ['vs']),
      InflectionRule.suffix('為た', '為る', ['-た'], ['vs']),
      InflectionRule.suffix('きた', 'くる', ['-た'], ['vk']),
      InflectionRule.suffix('来た', '来る', ['-た'], ['vk']),
      InflectionRule.suffix('來た', '來る', ['-た'], ['vk']),
      InflectionRule.suffix('いった', 'いく', ['-た'], ['v5']),
      InflectionRule.suffix('行った', '行く', ['-た'], ['v5']),
      InflectionRule.suffix('逝った', '逝く', ['-た'], ['v5']),
      InflectionRule.suffix('往った', '往く', ['-た'], ['v5']),
      InflectionRule.suffix('こうた', 'こう', ['-た'], ['v5']),
      InflectionRule.suffix('とうた', 'とう', ['-た'], ['v5']),
      InflectionRule.suffix('請うた', '請う', ['-た'], ['v5']),
      InflectionRule.suffix('乞うた', '乞う', ['-た'], ['v5']),
      InflectionRule.suffix('恋うた', '恋う', ['-た'], ['v5']),
      InflectionRule.suffix('問うた', '問う', ['-た'], ['v5']),
      InflectionRule.suffix('訪うた', '訪う', ['-た'], ['v5']),
      InflectionRule.suffix('宣うた', '宣う', ['-た'], ['v5']),
      InflectionRule.suffix('曰うた', '曰う', ['-た'], ['v5']),
      InflectionRule.suffix('給うた', '給う', ['-た'], ['v5']),
      InflectionRule.suffix('賜うた', '賜う', ['-た'], ['v5']),
      InflectionRule.suffix('揺蕩うた', '揺蕩う', ['-た'], ['v5']),
      InflectionRule.suffix('のたもうた', 'のたまう', ['-た'], ['v5']),
      InflectionRule.suffix('たもうた', 'たまう', ['-た'], ['v5']),
      InflectionRule.suffix('たゆとうた', 'たゆたう', ['-た'], ['v5']),
      InflectionRule.suffix('ました', 'ます', ['-た'], ['-ます']),
      InflectionRule.suffix('でした', '', ['-た'], ['-ません']),
      InflectionRule.suffix('かった', '', ['-た'], ['-ません', '-ん']),
    ],
  ),
  TransformSpec(
    id: '-ます',
    name: '-ます',
    rules: [
      InflectionRule.suffix('ます', 'る', ['-ます'], ['v1']),
      InflectionRule.wholeWord('いらっしゃいます', 'いらっしゃる', ['-ます'], ['v5d']),
      InflectionRule.wholeWord('ございます', 'ござる', ['-ます'], ['v5d']),
      InflectionRule.wholeWord('なさいます', 'なさる', ['-ます'], ['v5d']),
      InflectionRule.wholeWord('くださいます', 'くださる', ['-ます'], ['v5d']),
      InflectionRule.wholeWord('下さいます', '下さる', ['-ます'], ['v5d']),
      InflectionRule.wholeWord('おっしゃいます', 'おっしゃる', ['-ます'], ['v5d']),
      InflectionRule.wholeWord('仰います', '仰る', ['-ます'], ['v5d']),
      InflectionRule.wholeWord('仰有います', '仰有る', ['-ます'], ['v5d']),
      InflectionRule.suffix('います', 'う', ['-ます'], ['v5d']),
      InflectionRule.suffix('ひます', 'う', ['-ます'], ['v5d']),
      InflectionRule.suffix('きます', 'く', ['-ます'], ['v5d']),
      InflectionRule.suffix('ぎます', 'ぐ', ['-ます'], ['v5d']),
      InflectionRule.suffix('します', 'す', ['-ます'], ['v5d', 'v5s']),
      InflectionRule.suffix('ちます', 'つ', ['-ます'], ['v5d']),
      InflectionRule.suffix('にます', 'ぬ', ['-ます'], ['v5d']),
      InflectionRule.suffix('びます', 'ぶ', ['-ます'], ['v5d']),
      InflectionRule.suffix('みます', 'む', ['-ます'], ['v5d']),
      InflectionRule.suffix('ります', 'る', ['-ます'], ['v5d']),
      InflectionRule.suffix('じます', 'ずる', ['-ます'], ['vz']),
      InflectionRule.suffix('します', 'する', ['-ます'], ['vs']),
      InflectionRule.suffix('為ます', '為る', ['-ます'], ['vs']),
      InflectionRule.suffix('きます', 'くる', ['-ます'], ['vk']),
      InflectionRule.suffix('来ます', '来る', ['-ます'], ['vk']),
      InflectionRule.suffix('來ます', '來る', ['-ます'], ['vk']),
      InflectionRule.suffix('くあります', 'い', ['-ます'], ['adj-i']),
    ],
  ),
  TransformSpec(
    id: 'potential',
    name: 'potential',
    rules: [
      InflectionRule.suffix('れる', 'る', ['v1'], ['v1', 'v5d']),
      InflectionRule.suffix('える', 'う', ['v1'], ['v5d']),
      InflectionRule.suffix('ける', 'く', ['v1'], ['v5d']),
      InflectionRule.suffix('げる', 'ぐ', ['v1'], ['v5d']),
      InflectionRule.suffix('せる', 'す', ['v1'], ['v5d']),
      InflectionRule.suffix('てる', 'つ', ['v1'], ['v5d']),
      InflectionRule.suffix('ねる', 'ぬ', ['v1'], ['v5d']),
      InflectionRule.suffix('べる', 'ぶ', ['v1'], ['v5d']),
      InflectionRule.suffix('める', 'む', ['v1'], ['v5d']),
      InflectionRule.suffix('できる', 'する', ['v1'], ['vs']),
      InflectionRule.suffix('出来る', 'する', ['v1'], ['vs']),
      InflectionRule.suffix('これる', 'くる', ['v1'], ['vk']),
      InflectionRule.suffix('来れる', '来る', ['v1'], ['vk']),
      InflectionRule.suffix('來れる', '來る', ['v1'], ['vk']),
    ],
  ),
  TransformSpec(
    id: 'potential or passive',
    name: 'potential or passive',
    rules: [
      InflectionRule.suffix('られる', 'る', ['v1'], ['v1']),
      InflectionRule.suffix('ざれる', 'ずる', ['v1'], ['vz']),
      InflectionRule.suffix('ぜられる', 'ずる', ['v1'], ['vz']),
      InflectionRule.suffix('せられる', 'する', ['v1'], ['vs']),
      InflectionRule.suffix('為られる', '為る', ['v1'], ['vs']),
      InflectionRule.suffix('こられる', 'くる', ['v1'], ['vk']),
      InflectionRule.suffix('来られる', '来る', ['v1'], ['vk']),
      InflectionRule.suffix('來られる', '來る', ['v1'], ['vk']),
    ],
  ),
  TransformSpec(
    id: 'volitional',
    name: 'volitional',
    rules: [
      InflectionRule.suffix('よう', 'る', <String>[], ['v1']),
      InflectionRule.suffix('やう', 'る', <String>[], ['v1']),
      InflectionRule.suffix('おう', 'う', <String>[], ['v5']),
      InflectionRule.suffix('はう', 'う', <String>[], ['v5']),
      InflectionRule.suffix('こう', 'く', <String>[], ['v5']),
      InflectionRule.suffix('かう', 'く', <String>[], ['v5']),
      InflectionRule.suffix('ごう', 'ぐ', <String>[], ['v5']),
      InflectionRule.suffix('がう', 'ぐ', <String>[], ['v5']),
      InflectionRule.suffix('そう', 'す', <String>[], ['v5']),
      InflectionRule.suffix('さう', 'す', <String>[], ['v5']),
      InflectionRule.suffix('とう', 'つ', <String>[], ['v5']),
      InflectionRule.suffix('たう', 'つ', <String>[], ['v5']),
      InflectionRule.suffix('のう', 'ぬ', <String>[], ['v5']),
      InflectionRule.suffix('なう', 'ぬ', <String>[], ['v5']),
      InflectionRule.suffix('ぼう', 'ぶ', <String>[], ['v5']),
      InflectionRule.suffix('ばう', 'ぶ', <String>[], ['v5']),
      InflectionRule.suffix('もう', 'む', <String>[], ['v5']),
      InflectionRule.suffix('まう', 'む', <String>[], ['v5']),
      InflectionRule.suffix('ろう', 'る', <String>[], ['v5']),
      InflectionRule.suffix('らう', 'る', <String>[], ['v5']),
      InflectionRule.suffix('じよう', 'ずる', <String>[], ['vz']),
      InflectionRule.suffix('じやう', 'ずる', <String>[], ['vz']),
      InflectionRule.suffix('しよう', 'する', <String>[], ['vs']),
      InflectionRule.suffix('しやう', 'する', <String>[], ['vs']),
      InflectionRule.suffix('為よう', '為る', <String>[], ['vs']),
      InflectionRule.suffix('為やう', '為る', <String>[], ['vs']),
      InflectionRule.suffix('こよう', 'くる', <String>[], ['vk']),
      InflectionRule.suffix('こやう', 'くる', <String>[], ['vk']),
      InflectionRule.suffix('来よう', '来る', <String>[], ['vk']),
      InflectionRule.suffix('来やう', '来る', <String>[], ['vk']),
      InflectionRule.suffix('來よう', '來る', <String>[], ['vk']),
      InflectionRule.suffix('來やう', '來る', <String>[], ['vk']),
      InflectionRule.suffix('ましょう', 'ます', <String>[], ['-ます']),
      InflectionRule.suffix('ませう', 'ます', <String>[], ['-ます']),
      InflectionRule.suffix('かろう', 'い', <String>[], ['adj-i']),
      InflectionRule.suffix('からう', 'い', <String>[], ['adj-i']),
    ],
  ),
  TransformSpec(
    id: 'volitional slang',
    name: 'volitional slang',
    rules: [
      InflectionRule.suffix('よっか', 'る', <String>[], ['v1']),
      InflectionRule.suffix('おっか', 'う', <String>[], ['v5']),
      InflectionRule.suffix('こっか', 'く', <String>[], ['v5']),
      InflectionRule.suffix('ごっか', 'ぐ', <String>[], ['v5']),
      InflectionRule.suffix('そっか', 'す', <String>[], ['v5']),
      InflectionRule.suffix('とっか', 'つ', <String>[], ['v5']),
      InflectionRule.suffix('のっか', 'ぬ', <String>[], ['v5']),
      InflectionRule.suffix('ぼっか', 'ぶ', <String>[], ['v5']),
      InflectionRule.suffix('もっか', 'む', <String>[], ['v5']),
      InflectionRule.suffix('ろっか', 'る', <String>[], ['v5']),
      InflectionRule.suffix('じよっか', 'ずる', <String>[], ['vz']),
      InflectionRule.suffix('しよっか', 'する', <String>[], ['vs']),
      InflectionRule.suffix('為よっか', '為る', <String>[], ['vs']),
      InflectionRule.suffix('こよっか', 'くる', <String>[], ['vk']),
      InflectionRule.suffix('来よっか', '来る', <String>[], ['vk']),
      InflectionRule.suffix('來よっか', '來る', <String>[], ['vk']),
      InflectionRule.suffix('ましょっか', 'ます', <String>[], ['-ます']),
    ],
  ),
  TransformSpec(
    id: '-まい',
    name: '-まい',
    rules: [
      InflectionRule.suffix('まい', '', <String>[], ['v']),
      InflectionRule.suffix('まい', 'る', <String>[], ['v1']),
      InflectionRule.suffix('じまい', 'ずる', <String>[], ['vz']),
      InflectionRule.suffix('しまい', 'する', <String>[], ['vs']),
      InflectionRule.suffix('為まい', '為る', <String>[], ['vs']),
      InflectionRule.suffix('こまい', 'くる', <String>[], ['vk']),
      InflectionRule.suffix('来まい', '来る', <String>[], ['vk']),
      InflectionRule.suffix('來まい', '來る', <String>[], ['vk']),
      InflectionRule.suffix('まい', '', <String>[], ['-ます']),
    ],
  ),
  TransformSpec(
    id: '-おく',
    name: '-おく',
    rules: [
      InflectionRule.suffix('ておく', 'て', ['v5'], ['-て']),
      InflectionRule.suffix('でおく', 'で', ['v5'], ['-て']),
      InflectionRule.suffix('とく', 'て', ['v5'], ['-て']),
      InflectionRule.suffix('どく', 'で', ['v5'], ['-て']),
      InflectionRule.suffix('ないでおく', 'ない', ['v5'], ['adj-i']),
      InflectionRule.suffix('ないどく', 'ない', ['v5'], ['adj-i']),
    ],
  ),
  TransformSpec(
    id: '-いる',
    name: '-いる',
    rules: [
      InflectionRule.suffix('ている', 'て', ['v1'], ['-て']),
      InflectionRule.suffix('てゐる', 'て', ['v1'], ['-て']),
      InflectionRule.suffix('ておる', 'て', ['v5'], ['-て']),
      InflectionRule.suffix('てる', 'て', ['v1p'], ['-て']),
      InflectionRule.suffix('でいる', 'で', ['v1'], ['-て']),
      InflectionRule.suffix('でゐる', 'で', ['v1'], ['-て']),
      InflectionRule.suffix('でおる', 'で', ['v5'], ['-て']),
      InflectionRule.suffix('でる', 'で', ['v1p'], ['-て']),
      InflectionRule.suffix('とる', 'て', ['v5'], ['-て']),
      InflectionRule.suffix('ないでいる', 'ない', ['v1'], ['adj-i']),
      InflectionRule.suffix('ないでゐる', 'ない', ['v1'], ['adj-i']),
    ],
  ),
  TransformSpec(
    id: '-ふ',
    name: '-ふ',
    rules: [
      InflectionRule.suffix('ふ', 'う', <String>[], ['v5']),
    ],
  ),
  TransformSpec(
    id: '-き',
    name: '-き',
    rules: [
      InflectionRule.suffix('き', 'い', <String>[], ['adj-i']),
    ],
  ),
  TransformSpec(
    id: '-げ',
    name: '-げ',
    rules: [
      InflectionRule.suffix('げ', 'い', <String>[], ['adj-i']),
      InflectionRule.suffix('気', 'い', <String>[], ['adj-i']),
    ],
  ),
  TransformSpec(
    id: '-がる',
    name: '-がる',
    rules: [
      InflectionRule.suffix('がる', 'い', ['v5'], ['adj-i']),
    ],
  ),
  TransformSpec(
    id: '-やがる',
    name: '-やがる',
    rules: [
      InflectionRule.suffix('やがる', 'る', ['v5'], ['v1']),
      InflectionRule.suffix('いやがる', 'う', ['v5'], ['v5']),
      InflectionRule.suffix('きやがる', 'く', ['v5'], ['v5']),
      InflectionRule.suffix('ぎやがる', 'ぐ', ['v5'], ['v5']),
      InflectionRule.suffix('しやがる', 'す', ['v5'], ['v5']),
      InflectionRule.suffix('ちやがる', 'つ', ['v5'], ['v5']),
      InflectionRule.suffix('にやがる', 'ぬ', ['v5'], ['v5']),
      InflectionRule.suffix('びやがる', 'ぶ', ['v5'], ['v5']),
      InflectionRule.suffix('みやがる', 'む', ['v5'], ['v5']),
      InflectionRule.suffix('りやがる', 'る', ['v5'], ['v5']),
      InflectionRule.suffix('じやがる', 'ずる', ['v5'], ['vz']),
      InflectionRule.suffix('しやがる', 'する', ['v5'], ['vs']),
      InflectionRule.suffix('為やがる', '為る', ['v5'], ['vs']),
      InflectionRule.suffix('きやがる', 'くる', ['v5'], ['vk']),
      InflectionRule.suffix('来やがる', '来る', ['v5'], ['vk']),
      InflectionRule.suffix('來やがる', '來る', ['v5'], ['vk']),
    ],
  ),
  TransformSpec(
    id: '-え',
    name: '-え',
    rules: [
      InflectionRule.suffix('ねえ', 'ない', <String>[], ['adj-i']),
      InflectionRule.suffix('めえ', 'むい', <String>[], ['adj-i']),
      InflectionRule.suffix('みい', 'むい', <String>[], ['adj-i']),
      InflectionRule.suffix('ちぇえ', 'つい', <String>[], ['adj-i']),
      InflectionRule.suffix('ちい', 'つい', <String>[], ['adj-i']),
      InflectionRule.suffix('せえ', 'すい', <String>[], ['adj-i']),
      InflectionRule.suffix('ええ', 'いい', <String>[], ['adj-i']),
      InflectionRule.suffix('ええ', 'わい', <String>[], ['adj-i']),
      InflectionRule.suffix('ええ', 'よい', <String>[], ['adj-i']),
      InflectionRule.suffix('いぇえ', 'よい', <String>[], ['adj-i']),
      InflectionRule.suffix('うぇえ', 'わい', <String>[], ['adj-i']),
      InflectionRule.suffix('けえ', 'かい', <String>[], ['adj-i']),
      InflectionRule.suffix('げえ', 'がい', <String>[], ['adj-i']),
      InflectionRule.suffix('げえ', 'ごい', <String>[], ['adj-i']),
      InflectionRule.suffix('せえ', 'さい', <String>[], ['adj-i']),
      InflectionRule.suffix('めえ', 'まい', <String>[], ['adj-i']),
      InflectionRule.suffix('ぜえ', 'ずい', <String>[], ['adj-i']),
      InflectionRule.suffix('っぜえ', 'ずい', <String>[], ['adj-i']),
      InflectionRule.suffix('れえ', 'らい', <String>[], ['adj-i']),
      InflectionRule.suffix('れえ', 'らい', <String>[], ['adj-i']),
      InflectionRule.suffix('ちぇえ', 'ちゃい', <String>[], ['adj-i']),
      InflectionRule.suffix('でえ', 'どい', <String>[], ['adj-i']),
      InflectionRule.suffix('れえ', 'れい', <String>[], ['adj-i']),
      InflectionRule.suffix('べえ', 'ばい', <String>[], ['adj-i']),
      InflectionRule.suffix('てえ', 'たい', <String>[], ['adj-i']),
      InflectionRule.suffix('ねぇ', 'ない', <String>[], ['adj-i']),
      InflectionRule.suffix('めぇ', 'むい', <String>[], ['adj-i']),
      InflectionRule.suffix('みぃ', 'むい', <String>[], ['adj-i']),
      InflectionRule.suffix('ちぃ', 'つい', <String>[], ['adj-i']),
      InflectionRule.suffix('せぇ', 'すい', <String>[], ['adj-i']),
      InflectionRule.suffix('けぇ', 'かい', <String>[], ['adj-i']),
      InflectionRule.suffix('げぇ', 'がい', <String>[], ['adj-i']),
      InflectionRule.suffix('げぇ', 'ごい', <String>[], ['adj-i']),
      InflectionRule.suffix('せぇ', 'さい', <String>[], ['adj-i']),
      InflectionRule.suffix('めぇ', 'まい', <String>[], ['adj-i']),
      InflectionRule.suffix('ぜぇ', 'ずい', <String>[], ['adj-i']),
      InflectionRule.suffix('っぜぇ', 'ずい', <String>[], ['adj-i']),
      InflectionRule.suffix('れぇ', 'らい', <String>[], ['adj-i']),
      InflectionRule.suffix('でぇ', 'どい', <String>[], ['adj-i']),
      InflectionRule.suffix('れぇ', 'れい', <String>[], ['adj-i']),
      InflectionRule.suffix('べぇ', 'ばい', <String>[], ['adj-i']),
      InflectionRule.suffix('てぇ', 'たい', <String>[], ['adj-i']),
    ],
  ),
  TransformSpec(
    id: 'n-slang',
    name: 'n-slang',
    rules: [
      InflectionRule.suffix('んなさい', 'りなさい', <String>[], ['-なさい']),
      InflectionRule.suffix('らんない', 'られない', ['adj-i'], ['adj-i']),
      InflectionRule.suffix('んない', 'らない', ['adj-i'], ['adj-i']),
      InflectionRule.suffix('んなきゃ', 'らなきゃ', <String>[], ['-ゃ']),
      InflectionRule.suffix('んなきゃ', 'れなきゃ', <String>[], ['-ゃ']),
    ],
  ),
  TransformSpec(
    id: 'imperative negative slang',
    name: 'imperative negative slang',
    rules: [
      InflectionRule.suffix('んな', 'る', <String>[], ['v']),
    ],
  ),
  TransformSpec(
    id: 'kansai-ben negative',
    name: 'kansai-ben',
    rules: [
      InflectionRule.suffix('へん', 'ない', <String>[], ['adj-i']),
      InflectionRule.suffix('ひん', 'ない', <String>[], ['adj-i']),
      InflectionRule.suffix('せえへん', 'しない', <String>[], ['adj-i']),
      InflectionRule.suffix('へんかった', 'なかった', ['-た'], ['-た']),
      InflectionRule.suffix('ひんかった', 'なかった', ['-た'], ['-た']),
      InflectionRule.suffix('うてへん', 'ってない', <String>[], ['adj-i']),
    ],
  ),
  TransformSpec(
    id: 'kansai-ben -て',
    name: 'kansai-ben',
    rules: [
      InflectionRule.suffix('うて', 'って', ['-て'], ['-て']),
      InflectionRule.suffix('おうて', 'あって', ['-て'], ['-て']),
      InflectionRule.suffix('こうて', 'かって', ['-て'], ['-て']),
      InflectionRule.suffix('ごうて', 'がって', ['-て'], ['-て']),
      InflectionRule.suffix('そうて', 'さって', ['-て'], ['-て']),
      InflectionRule.suffix('ぞうて', 'ざって', ['-て'], ['-て']),
      InflectionRule.suffix('とうて', 'たって', ['-て'], ['-て']),
      InflectionRule.suffix('どうて', 'だって', ['-て'], ['-て']),
      InflectionRule.suffix('のうて', 'なって', ['-て'], ['-て']),
      InflectionRule.suffix('ほうて', 'はって', ['-て'], ['-て']),
      InflectionRule.suffix('ぼうて', 'ばって', ['-て'], ['-て']),
      InflectionRule.suffix('もうて', 'まって', ['-て'], ['-て']),
      InflectionRule.suffix('ろうて', 'らって', ['-て'], ['-て']),
      InflectionRule.suffix('ようて', 'やって', ['-て'], ['-て']),
      InflectionRule.suffix('ゆうて', 'いって', ['-て'], ['-て']),
    ],
  ),
  TransformSpec(
    id: 'kansai-ben -た',
    name: 'kansai-ben',
    rules: [
      InflectionRule.suffix('うた', 'った', ['-た'], ['-た']),
      InflectionRule.suffix('おうた', 'あった', ['-た'], ['-た']),
      InflectionRule.suffix('こうた', 'かった', ['-た'], ['-た']),
      InflectionRule.suffix('ごうた', 'がった', ['-た'], ['-た']),
      InflectionRule.suffix('そうた', 'さった', ['-た'], ['-た']),
      InflectionRule.suffix('ぞうた', 'ざった', ['-た'], ['-た']),
      InflectionRule.suffix('とうた', 'たった', ['-た'], ['-た']),
      InflectionRule.suffix('どうた', 'だった', ['-た'], ['-た']),
      InflectionRule.suffix('のうた', 'なった', ['-た'], ['-た']),
      InflectionRule.suffix('ほうた', 'はった', ['-た'], ['-た']),
      InflectionRule.suffix('ぼうた', 'ばった', ['-た'], ['-た']),
      InflectionRule.suffix('もうた', 'まった', ['-た'], ['-た']),
      InflectionRule.suffix('ろうた', 'らった', ['-た'], ['-た']),
      InflectionRule.suffix('ようた', 'やった', ['-た'], ['-た']),
      InflectionRule.suffix('ゆうた', 'いった', ['-た'], ['-た']),
    ],
  ),
  TransformSpec(
    id: 'kansai-ben -たら',
    name: 'kansai-ben',
    rules: [
      InflectionRule.suffix('うたら', 'ったら', <String>[], <String>[]),
      InflectionRule.suffix('おうたら', 'あったら', <String>[], <String>[]),
      InflectionRule.suffix('こうたら', 'かったら', <String>[], <String>[]),
      InflectionRule.suffix('ごうたら', 'がったら', <String>[], <String>[]),
      InflectionRule.suffix('そうたら', 'さったら', <String>[], <String>[]),
      InflectionRule.suffix('ぞうたら', 'ざったら', <String>[], <String>[]),
      InflectionRule.suffix('とうたら', 'たったら', <String>[], <String>[]),
      InflectionRule.suffix('どうたら', 'だったら', <String>[], <String>[]),
      InflectionRule.suffix('のうたら', 'なったら', <String>[], <String>[]),
      InflectionRule.suffix('ほうたら', 'はったら', <String>[], <String>[]),
      InflectionRule.suffix('ぼうたら', 'ばったら', <String>[], <String>[]),
      InflectionRule.suffix('もうたら', 'まったら', <String>[], <String>[]),
      InflectionRule.suffix('ろうたら', 'らったら', <String>[], <String>[]),
      InflectionRule.suffix('ようたら', 'やったら', <String>[], <String>[]),
      InflectionRule.suffix('ゆうたら', 'いったら', <String>[], <String>[]),
    ],
  ),
  TransformSpec(
    id: 'kansai-ben -たり',
    name: 'kansai-ben',
    rules: [
      InflectionRule.suffix('うたり', 'ったり', <String>[], <String>[]),
      InflectionRule.suffix('おうたり', 'あったり', <String>[], <String>[]),
      InflectionRule.suffix('こうたり', 'かったり', <String>[], <String>[]),
      InflectionRule.suffix('ごうたり', 'がったり', <String>[], <String>[]),
      InflectionRule.suffix('そうたり', 'さったり', <String>[], <String>[]),
      InflectionRule.suffix('ぞうたり', 'ざったり', <String>[], <String>[]),
      InflectionRule.suffix('とうたり', 'たったり', <String>[], <String>[]),
      InflectionRule.suffix('どうたり', 'だったり', <String>[], <String>[]),
      InflectionRule.suffix('のうたり', 'なったり', <String>[], <String>[]),
      InflectionRule.suffix('ほうたり', 'はったり', <String>[], <String>[]),
      InflectionRule.suffix('ぼうたり', 'ばったり', <String>[], <String>[]),
      InflectionRule.suffix('もうたり', 'まったり', <String>[], <String>[]),
      InflectionRule.suffix('ろうたり', 'らったり', <String>[], <String>[]),
      InflectionRule.suffix('ようたり', 'やったり', <String>[], <String>[]),
      InflectionRule.suffix('ゆうたり', 'いったり', <String>[], <String>[]),
    ],
  ),
  TransformSpec(
    id: 'kansai-ben -く',
    name: 'kansai-ben',
    rules: [
      InflectionRule.suffix('う', 'く', <String>[], ['-く']),
      InflectionRule.suffix('こう', 'かく', <String>[], ['-く']),
      InflectionRule.suffix('ごう', 'がく', <String>[], ['-く']),
      InflectionRule.suffix('そう', 'さく', <String>[], ['-く']),
      InflectionRule.suffix('とう', 'たく', <String>[], ['-く']),
      InflectionRule.suffix('のう', 'なく', <String>[], ['-く']),
      InflectionRule.suffix('ぼう', 'ばく', <String>[], ['-く']),
      InflectionRule.suffix('もう', 'まく', <String>[], ['-く']),
      InflectionRule.suffix('ろう', 'らく', <String>[], ['-く']),
      InflectionRule.suffix('よう', 'よく', <String>[], ['-く']),
      InflectionRule.suffix('しゅう', 'しく', <String>[], ['-く']),
    ],
  ),
  TransformSpec(
    id: 'kansai-ben adjective -て',
    name: 'kansai-ben',
    rules: [
      InflectionRule.suffix('うて', 'くて', ['-て'], ['-て']),
      InflectionRule.suffix('こうて', 'かくて', ['-て'], ['-て']),
      InflectionRule.suffix('ごうて', 'がくて', ['-て'], ['-て']),
      InflectionRule.suffix('そうて', 'さくて', ['-て'], ['-て']),
      InflectionRule.suffix('とうて', 'たくて', ['-て'], ['-て']),
      InflectionRule.suffix('のうて', 'なくて', ['-て'], ['-て']),
      InflectionRule.suffix('ぼうて', 'ばくて', ['-て'], ['-て']),
      InflectionRule.suffix('もうて', 'まくて', ['-て'], ['-て']),
      InflectionRule.suffix('ろうて', 'らくて', ['-て'], ['-て']),
      InflectionRule.suffix('ようて', 'よくて', ['-て'], ['-て']),
      InflectionRule.suffix('しゅうて', 'しくて', ['-て'], ['-て']),
    ],
  ),
  TransformSpec(
    id: 'kansai-ben adjective negative',
    name: 'kansai-ben',
    rules: [
      InflectionRule.suffix('うない', 'くない', ['adj-i'], ['adj-i']),
      InflectionRule.suffix('こうない', 'かくない', ['adj-i'], ['adj-i']),
      InflectionRule.suffix('ごうない', 'がくない', ['adj-i'], ['adj-i']),
      InflectionRule.suffix('そうない', 'さくない', ['adj-i'], ['adj-i']),
      InflectionRule.suffix('とうない', 'たくない', ['adj-i'], ['adj-i']),
      InflectionRule.suffix('のうない', 'なくない', ['adj-i'], ['adj-i']),
      InflectionRule.suffix('ぼうない', 'ばくない', ['adj-i'], ['adj-i']),
      InflectionRule.suffix('もうない', 'まくない', ['adj-i'], ['adj-i']),
      InflectionRule.suffix('ろうない', 'らくない', ['adj-i'], ['adj-i']),
      InflectionRule.suffix('ようない', 'よくない', ['adj-i'], ['adj-i']),
      InflectionRule.suffix('しゅうない', 'しくない', ['adj-i'], ['adj-i']),
    ],
  ),
];
